apiVersion: networking.k8s.io/v1  #  Ingress 리소스의 API 버전 (Kubernetes 1.19 이상에서 v1 사용)
kind: Ingress                     #  리소스 타입: Ingress (브라우저 ↔ 클러스터 입구 역할)
metadata:
  name: fastapi-ingress           #  이 Ingress 리소스의 이름
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #  정규식 캡쳐(/(.*))된 경로를 실제 서비스에 /$1 형태로 전달함
    #  예: /status → /status 로 그대로 전달됨
spec:
  rules:
    - host: fastapi.192.168.49.2.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-service
                port:
                  number: 8000