apiVersion: apps/v1
kind: Deployment
metadata:
  name: anlz-wrk-deploy              # ← 디플로이 이름 (kubectl get deployment 시 출력됨)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anlz-wrk           # ← 여기랑 ↓ template.metadata.labels.app 이랑 **반드시 일치해야 함**
  template:
    metadata:
      labels:
        app: anlz-wrk         # ← Pod에 찍히는 라벨. selector랑 같아야 디플로이가 이 Pod 관리함
        # ※ 여기 라벨이 실제 Pod에 붙는 라벨이 됨
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: analyzer-worker      # ← 컨테이너 이름. Pod 안에서만 구분용 (kubectl describe pod 보면 나옴)
          image: ghcr.io/ajh9789/analyzer_worker:latest
          imagePullPolicy: Always
          command: [ "celery" ]
          args: [ "-A", "analyzer_worker", "worker", "-Q", "analyzer_queue", "--loglevel=info", "--concurrency=1","--pool=solo" ]
          envFrom:
            - configMapRef:
                name: whisper-config
            - secretRef:
                name: whisper-secret
          env:
            - name: REDIS_HOST
              value: redis
            - name: DOCKER
              value: "1"