apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  labels:
    app: fastapi-svc
spec:
  type: {{ .Values.fastapi.service.type }}
  selector:
    app: fastapi
  ports:
    - port: {{ .Values.fastapi.service.port }}
      targetPort: {{ .Values.fastapi.service.targetPort }}
