apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc        # 서비스 리소스 이름 (자유롭게 작명, 일반적으로 svc 붙임)
  labels:
    app: fastapi-svc       # 이건 크게 중요하진 않음 (디버깅용 태그일 뿐)

spec:
  type: ClusterIP
  selector:
    app: fastapi           # ← 이게 진짜 중요. Pod의 app 라벨과 **일치해야 연결**됨
  ports:
    - port: 8000
      targetPort: 8000