apiVersion: networking.k8s.io/v1  #  Ingress 리소스의 API 버전 (Kubernetes 1.19 이상에서 v1 사용)
kind: Ingress                     #  리소스 타입: Ingress (브라우저 ↔ 클러스터 입구 역할)
metadata:
  name: fastapi-ingress           #  이 Ingress 리소스의 이름
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #  정규식 캡쳐(/(.*))된 경로를 실제 서비스에 /$1 형태로 전달함
    #  예: /status → /status 로 그대로 전달됨
spec:
  rules:
    - host: localhost             # 브라우저에서 접속할 host (도메인)
      http:
        paths:
          - path: /fastapi(/|$)(.*)         # 모든 경로를 대상으로 라우팅
            pathType: Prefix      #  path는 접두사(Prefix) 방식 매칭 (정규식과 함께 써야 작동)
            backend:
              service:
                name: fastapi-svc   # 요청을 포워딩할 대상 서비스 이름 (Service 리소스 이름)
                port:
                  number: 8000          # 그 서비스의 포트 (fastapi가 8000에서 실행되므로 맞음)
          - path: /prometheus(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: prometheus-svc
                port:
                  number: 9090
          - path: /grafana(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: grafana-svc
                port:
                  number: 3000
