apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s  # 메트릭 수집 주기 (기본: 1분 → 5초로 조정)

    scrape_configs:
      - job_name: 'fastapi_app'
        static_configs:
          - targets: [ 'fastapi-svc.default.svc.cluster.local:8000' ]  # FastAPI 서비스 메트릭 수집 대상