apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-wkr-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stt-wkr
  template:
    metadata:
      labels:
        app: stt-wkr
    spec:
      containers:
        - name: stt-worker
          image: ajh9789/stt_worker:latest
          resources:
            requests:
              cpu: 500m         # 0.5 코어
              memory: 512Mi
            limits:
              cpu: 1000m        # 최대 1 코어
              memory: 1536Mi
          imagePullPolicy: Always
          #커멘드
          command: [ "celery" ]
          args: [ "-A", "stt_worker", "worker", "--loglevel=info", "-Q", "stt_queue", "--concurrency=1","--pool=solo" ]
          #환경설정
          envFrom:
            - configMapRef:
                name: stt-config
            - secretRef:
                name: whisper-secret
          env:
            - name: REDIS_HOST
              value: redis
            - name: DOCKER
              value: "1"
          #볼륨 붙이는곳
          volumeMounts:
            - name: model-volume
              mountPath: /app/models
      volumes: #실제 볼륨
        - name: model-volume
          persistentVolumeClaim:
            claimName: pvc-models