replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: [ ]

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }


securityContext: { }

service:
  type: ClusterIP
  port: 80

  tls: [ ]

resources: { }

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


volumes: [ ]

volumeMounts: [ ]

nodeSelector: { }

tolerations: [ ]

affinity: { }

redis:
  image:
    repository: redis
    tag: 7.2
    pullPolicy: IfNotPresent
  containerPort: 6379
  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379

fastapi:
  image:
    repository: ghcr.io/ajh9789/fastapi_service
    tag: latest
    pullPolicy: Always

  containerPort: 8000

  command: [ "uvicorn" ]
  args: [ "fastapi_service:app", "--host", "0.0.0.0", "--port", "8000" ]

  env:
    - name: REDIS_HOST
      value: redis

  envFrom:
    - configMapRef:
        name: whisper-config
    - secretRef:
        name: whisper-secret

  livenessProbe:
    httpGet:
      path: /
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /status
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 2

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

analyzer:
  replicas: 1
  image:
    repository: ghcr.io/ajh9789/analyzer_worker
    tag: latest
    pullPolicy: Always
  command:
    - "celery"
  args: [ "-A", "analyzer_worker", "worker", "-Q", "analyzer_queue", "--loglevel=info", "--concurrency=1","--pool=solo" ]
  envFrom:
    - configMapRef:
        name: whisper-config
    - secretRef:
        name: whisper-secret
  env:
    - name: REDIS_HOST
      value: redis
    - name: DOCKER
      value: "1"


sttWorker:
  replicas: 2
  image:
    repository: ghcr.io/ajh9789/stt_worker
    tag: latest
    pullPolicy: Always
  containerPort: 8000  # 실제 포트 입력
  command: [ "celery" ]
  args: [ "-A", "stt_worker", "worker", "--loglevel=info", "-Q", "stt_queue", "--concurrency=1", "--pool=solo" ]
  env:
    - name: REDIS_HOST
      value: redis
    - name: DOCKER
      value: "1"
    - name: MODEL_PATH
      value: /app/models
    - name: MODEL_SIZE
      value: medium  # 또는 tiny, small, medium
  envFrom:
    - configMapRef:
        name: whisper-config
    - secretRef:
        name: whisper-secret
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 3072Mi

sttWorkerHPA:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

whisperConfig:
  REDIS_HOST: redis
  MODEL_PATH: /app/models
  MODEL_SIZE: medium
  DOCKER: "1"

persistentVolume:
  name: pv-models
  storage: 2Gi
  path: /mnt/models
  storageClassName: ""

persistentVolumeClaim:
  name: pvc-models
  storage: 2Gi
  storageClassName: ""

ingress:
  enabled: true
  name: whisper-ingress
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "self-signed"
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
    - hosts:
        - local.fastapi.test
      secretName: whisper-tls
  rules:
    - host: local.fastapi.test
      http:
        paths:
          - path: /fastapi
            pathType: Prefix
            backend:
              service:
                name: fastapi-svc
                port:
                  number: 8000
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: monitoring-grafana
                port:
                  number: 80
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus-operated
                port:
                  number: 9090



grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
    port: 80
  # 자동 대시보드 ConfigMap을 감시하는 사이드카 설정
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL  # default 네임스페이스 외에 다른 것도 허용 시 ALL
  # Prometheus, Loki 데이터소스 자동 등록
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-operated.default.svc.cluster.local:9090
          isDefault: true
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.default.svc.cluster.local:3100
          isDefault: false  # 명시 안해서 그라파다 포드하나죽음
  # 대시보드 로딩용 provider 설정
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  # 대시보드를 로딩할 ConfigMap 이름 매핑
  dashboardsConfigMaps:
    default: grafana-dashboards

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: { }
    additionalServiceMonitors:
      - name: fastapi-monitor
        selector:
          matchLabels:
            app: fastapi
        namespaceSelector:
          matchNames:
            - default
        endpoints:
          - port: http
            path: /metrics

loki:
  enabled: true

promtail:
  enabled: true
  config:
    snippets:
      pipelineStages:
        - cri: { }
      extraScrapeConfigs: |
        - job_name: fastapi-logs
          static_configs:
            - targets:
                - localhost
              labels:
                job: fastapi
                __path__: /var/log/containers/*fastapi*.log

certManager:
  issuerName: self-signed
  domain: local.fastapi.test
  secretName: whisper-tls
  duration: 2160h
  renewBefore: 360h