apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analyzer-worker
  template:
    metadata:
      labels:
        app: analyzer-worker
    spec:
      containers:
        - name: analyzer-worker
          image: ajh9789/analyzer_worker:latest
          imagePullPolicy: Always
          command: ["celery"]
          args: ["-A", "analyzer_worker", "worker", "-Q", "analyzer_queue", "--loglevel=info", "--concurrency=1","--pool=solo"]
          env:
            - name: REDIS_HOST
              value: redis
            - name: DOCKER
              value: "1"