apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener-service
  template:
    metadata:
      labels:
        app: listener-service
    spec:
      containers:
        - name: listener-service
          image: ajh9789/listener_service:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis