apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: stt-worker
  template:
    metadata:
      labels:
        app: stt-worker
    spec:
      containers:
        - name: stt-worker
          image: ajh9789/stt_worker:latest
          imagePullPolicy: Always
          command: [ "celery" ]
          args: [ "-A", "stt_worker", "worker", "--loglevel=info", "-Q", "stt_queue", "--concurrency=1","--pool=solo" ]
          env:
            - name: REDIS_HOST
              value: redis
            - name: DOCKER
              value: "1"