apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service        # ← 하이픈 사용
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-service     # ← 하이픈
  template:
    metadata:
      labels:
        app: fastapi-service   # ← 하이픈
    spec:
      containers: # 네임은 리스트형식
        - name: fastapi-service # pod안에 여러 컨테이너를 정의 가능하기때문
          image: ajh9789/fastapi_service:latest  # ← 이건 DockerHub이므로 언더스코어 OK
          imagePullPolicy: Always
          #포트
          ports:
            - containerPort: 8000
          #커맨드
          command: [ "uvicorn" ]
          args: [ "fastapi_service:app", "--host", "0.0.0.0", "--port", "8000" ]
          #환경
          envFrom:
            - configMapRef:
                name: whisper-config
            - secretRef:
                name: whisper-secret
          env:
            - name: REDIS_HOST
              value: redis

          #??이건 아직뭔지모름
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          #??이것도모름
          readinessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi-service       # ← 반드시 Deployment와 일치해야 함
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
