apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stt-worker
  template:
    metadata:
      labels:
        app: stt-worker
    spec:
      containers:
        - name: stt-worker
          image: ajh9789/stt_worker:latest
          imagePullPolicy: Always
          #커멘드
          command: [ "celery" ]
          args: [ "-A", "stt_worker", "worker", "--loglevel=info", "-Q", "stt_queue" ]
          #args: [ "-A", "stt_worker", "worker", "--loglevel=info", "-Q", "stt_queue", "--concurrency=1","--pool=solo" ]
          resources:
            limits:
              nvidia.com/gpu: 1       # GPU 1개 강제 할당 (절대값)
            requests:
              memory: 4Gi           # 최소 4GiB RAM 예약 (보장됨)
              cpu: 1               # 최소 CPU 1개 보장 (다른 Pod과 공유 가능)
          #환경설정
          envFrom:
            - configMapRef:
                name: whisper-config
            - secretRef:
                name: whisper-secret
          env:
            - name: REDIS_HOST
              value: redis
            - name: DOCKER
              value: "1"
          #볼륨 붙이는곳
          volumeMounts:
            - name: model-volume
              mountPath: /app/models
      volumes: #실제 볼륨
        - name: model-volume
          persistentVolumeClaim:
            claimName: pvc-models