apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-models
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/models #로컬 경로 (minikube vm 내부)

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi